version: '0.1'
services:
  PostgreSQL:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=progetto123
      - POSTGRES_USER=pasquale
      - PGUSER=pasquale
      - POSTGRES_DB=ristorante
      - PGDATA=/pgdata
    volumes:
      - ./pgdata:/pgdata
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "ristorante", "-U", "pasquale" ]
      interval: 10s
      timeout: 5s
      retries: 5
